# ------------------------------------------------------------------------------
# -----                                                                    -----
# -----                        AN1792 Project                              -----
# -----                                                                    -----
# -----                           Gate Lab                                 -----
# -----                     Northwestern University                        -----
# -----                                                                    -----
# ------------------------------------------------------------------------------
#
# Written by: Anne Forsyth
# Summary: Run SCTransform and perform Harmony integration in Seurat
#
#-------------------------------------------------------------------------------

# Load libraries
suppressMessages({
  library("plyr")
  library("dplyr")
  library("tidyverse")
  library("Seurat")
  library("harmony")
})

# Define output folder
output_dir <- "/path/to/integration/output/"

# Create subfolders
dir.create(paste0(output_dir, "data"), showWarnings = FALSE, recursive = TRUE)
dir.create(paste0(output_dir, "plots"), showWarnings = FALSE, recursive = TRUE)

# Load post-QC Seurat objects
s1 <- readRDS("/path/to/lecanemab/QC/output/s_post_qc.rds")
s2 <- readRDS("/path/to/AN1792/QC/output/s_post_qc.rds")

# Define AN1792 samples to keep based on quality  
samples_keep <- c("102.1", "102.16", "102.17", "102.19", "102.22")
samples_keep <- c(paste0(samples_keep, "_pool1"), paste0(samples_keep, "_pool2"))
s2 <- subset(s2, sample_id %in% samples_keep)

# Merge raw counts
s1 <- JoinLayers(s1)
s2 <- JoinLayers(s2)

# Update pool names to distinguish AN1792 and LCMB
s1$pool[grep("pool", s1$pool)] <- paste0("LCMB_", s1$pool[grep("pool", s1$pool)])
s2$pool <- paste0("AN1792_", s2$pool)
s <- merge(s1, s2, project = "AN1792_scFRP")

# Split layers by sample ID 
s <- JoinLayers(s)
s[["RNA"]] <- split(s[["RNA"]], f = s$sample_id)

# Run SCTransform, regressing out mitochondrial expression
s <- SCTransform(s, assay = "RNA", vars.to.regress = "percent.mt")

# Run PCA (50 PCs generated by default)
s <- RunPCA(s, verbose = F)

# Run Harmony integration
s <- IntegrateLayers(object = s, method = HarmonyIntegration, normalization.method = 'SCT', orig.reduction = 'pca', verbose = F, new.reduction = "harmony")

# Determine number of PCs to use for UMAP
ElbowPlot(s, ndims = 50)

# Generate UMAP
s <- RunUMAP(s, dims = 1:30, reduction = "harmony", reduction.name = "harmonyumap")

# Add column for general sample ID (merged across pools)
s$sample_merged <- str_split_fixed(s$sample_id, "_", 2)[,1]

# Log-normalize raw counts for visualization 
orig_default_assay <- DefaultAssay(s)
DefaultAssay(s) <- "RNA"
s <- NormalizeData(s)
DefaultAssay(s) <- orig_default_assay

# Save integrated object
saveRDS(s, file = paste0(output_dir, "data/s_harmony.rds"))




